#!/bin/bash

# Cleanup old lib files except init script and styles
find ./shared -type f -not -name 'initColorPicker.js' -not -name 'toolbar.css' -delete

# Copy new ones
cp ./node_modules/pdfjs-dist/build/pdf.js ./shared/
cp ./node_modules/pdfjs-dist/build/pdf.worker.js ./shared/
cp ./node_modules/pdfjs-dist/web/pdf_viewer.js ./shared/
cp ./node_modules/pdfjs-dist/web/pdf_viewer.css ./shared/

# Move the now updated folder
cp -rf ./shared ./dist/